version: 2.1 

 

jobs: 

  build-and-test:  

    machine: 

      image: ubuntu:20.04

        

    steps: 

      - checkout 

      - run: make deps 

      - run: make test       

workflows: 

  basic:  

    jobs: 

      - build-and-test 